return {	{ type = "reward"  	    , is_record = true         },
			{ type = "upgrade"		, name = "warehouse"		, min = 2 },
			{ type = "technology"	, name = "forestation"		, min = 2 },
			{ type = "recruit"		, name = "swordsman"		, is_record = true },
			{ type = "explore"      , is_record = true         },
			{ type = "build"		, name = "dwelling"	 		, min = 2 },
			{ type = "build"		, name = "dwelling"	 		, min = 3 },
			{ type = "build"		, name = "woodcutter"		, min = 2 },
			{ type = "build"		, name = "woodcutter"		, min = 3 },
			{ type = "build"		, name = "quarrier"	    	, min = 2 },
			{ type = "build"		, name = "quarrier"	    	, min = 3 },
			{ type = "build"		, name = "miner"	    	, min = 2 },
			{ type = "build"		, name = "miner"	    	, min = 3 },
			{ type = "build"		, name = "farmer"	    	, min = 2 },
			{ type = "build"		, name = "farmer"	    	, min = 3 },
			{ type = "explore"		, is_record = true         },
			{ type = "upgrade"		, name = "barracks"			, min = 4 },
			{ type = "recruit"		, name = "sentinel"	    	, is_record = true },
			{ type = "explore"		, is_record = true         },
			{ type = "upgrade"		, name = "hospital"			, min = 4 },
			{ type = "reward"  	    , is_record = true         },
			{ type = "upgrade"		, name = "materialDepot"	, min = 3 },
			{ type = "explore"		, is_record = true         },
			{ type = "upgrade"		, name = "wall"				, min = 4 },
			{ type = "upgrade"		, name = "tower"        	, min = 4 },
			{ type = "upgrade"		, name = "dragonEyrie"		, min = 2 },
			{ type = "reward"  	    , is_record = true         },
			-- { type = "upgrade"		, name = "watchTower"		, min = 4 },
			-- { type = "reward"  	    , is_record = true         },
			{ type = "explore"		, is_record = true         },
			{ type = "upgrade"		, name = "dragonEyrie"		, min = 3 },
			{ type = "reward"  	    , is_record = true         },
			{ type = "upgrade"		, name = "keep"	 			, min = 6 },
			{ type = "upgrade"		, name = "blackSmith"		, min = 1 },
			{ type = "encourage"   },
			{ type = "explore"		, is_record = true         },
			{ type = "upgrade"		, name = "dwelling"			, min = 5 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 5 },
			{ type = "upgrade"		, name = "quarrier"			, min = 5 },
			{ type = "upgrade"		, name = "miner"			, min = 5 },
			{ type = "upgrade"		, name = "farmer"			, min = 5 },
			{ type = "reward"  	    , is_record = true         },
			{ type = "upgrade"		, name = "barracks"			, min = 5 },
			{ type = "explore"		, is_record = true         },
			{ type = "upgrade"		, name = "dwelling"			, min = 6 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 6 },
			{ type = "upgrade"		, name = "quarrier"			, min = 6 },
			{ type = "upgrade"		, name = "miner"			, min = 6 },
			{ type = "upgrade"		, name = "farmer"			, min = 6 },
			{ type = "reward"  	    , is_record = true         },
			{ type = "upgrade"		, name = "barracks"			, min = 6 },
			{ type = "recruit"		, name = "ranger"	    	, is_record = true },
			{ type = "upgrade"		, name = "wall"				, min = 6 },
			{ type = "upgrade"		, name = "keep"				, min = 7 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16" 	  },
			{ type = "upgrade"		, name = "dwelling"			, min = 7 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 7 },
			{ type = "upgrade"		, name = "quarrier"			, min = 7 },
			{ type = "upgrade"		, name = "miner"			, min = 7 },
			{ type = "upgrade"		, name = "farmer"			, min = 7 },
			{ type = "upgrade"		, name = "barracks"			, min = 7 },
			{ type = "explore"		, is_record = true     	   },
			{ type = "upgrade"		, name = "wall"				, min = 7 },
			{ type = "upgrade"		, name = "keep"				, min = 8 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16"  	  },
			{ type = "upgrade"		, name = "dwelling"			, min = 8 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 8 },
			{ type = "upgrade"		, name = "quarrier"			, min = 8 },
			{ type = "upgrade"		, name = "miner"			, min = 8 },
			{ type = "upgrade"		, name = "farmer"			, min = 8 },
			{ type = "upgrade"		, name = "barracks"			, min = 8 },
			{ type = "recruit"		, name = "crossbowman"		, is_record = true },
			{ type = "upgrade"		, name = "wall"				, min = 8 },
			{ type = "upgrade"		, name = "keep"				, min = 9 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16"  	  },
			{ type = "upgrade"		, name = "dwelling"			, min = 9 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 9 },
			{ type = "upgrade"		, name = "quarrier"			, min = 9 },
			{ type = "upgrade"		, name = "miner"			, min = 9 },
			{ type = "upgrade"		, name = "farmer"			, min = 9 },
			{ type = "upgrade"		, name = "barracks"			, min = 9 },
			{ type = "explore"		, is_record = true     	   },
			{ type = "upgrade"		, name = "wall"				, min = 9  },
			{ type = "upgrade"		, name = "keep"				, min = 10 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16"  	   },
			{ type = "upgrade"		, name = "dwelling"			, min = 10 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 10 },
			{ type = "upgrade"		, name = "quarrier"			, min = 10 },
			{ type = "upgrade"		, name = "miner"			, min = 10 },
			{ type = "upgrade"		, name = "farmer"			, min = 10 },
			{ type = "upgrade"		, name = "barracks"			, min = 10 },
			{ type = "recruit"		, name = "lancer"	    	, is_record = true },
			{ type = "upgrade"		, name = "wall"				, min = 10 },
			{ type = "upgrade"		, name = "keep"				, min = 11 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16"  	   },
			{ type = "upgrade"		, name = "dwelling"			, min = 11 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 11 },
			{ type = "upgrade"		, name = "quarrier"			, min = 11 },
			{ type = "upgrade"		, name = "miner"			, min = 11 },
			{ type = "upgrade"		, name = "farmer"			, min = 11 },
			{ type = "upgrade"		, name = "barracks"			, min = 11 },
			{ type = "explore"		, is_record = true     	   },
			{ type = "upgrade"		, name = "wall"				, min = 11 },
			{ type = "upgrade"		, name = "keep"				, min = 12 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16"  	   },
			{ type = "upgrade"		, name = "dwelling"			, min = 12 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 12 },
			{ type = "upgrade"		, name = "quarrier"			, min = 12 },
			{ type = "upgrade"		, name = "miner"			, min = 12 },
			{ type = "upgrade"		, name = "farmer"			, min = 12 },
			{ type = "upgrade"		, name = "barracks"			, min = 12 },
			{ type = "recruit"		, name = "horseArcher"		, is_record = true },
			{ type = "upgrade"		, name = "wall"				, min = 12 },
			{ type = "upgrade"		, name = "keep"				, min = 13 },
			{ type = "unlock"		, name = "15,10,11,12,13,14,16"  	   },
			{ type = "upgrade"		, name = "dwelling"			, min = 13 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 13 },
			{ type = "upgrade"		, name = "quarrier"			, min = 13 },
			{ type = "upgrade"		, name = "miner"			, min = 13 },
			{ type = "upgrade"		, name = "farmer"			, min = 13 },
			{ type = "upgrade"		, name = "barracks"			, min = 13 },
			{ type = "explore"		, is_record = true     	   },
			{ type = "upgrade"		, name = "wall"				, min = 13 },
			{ type = "upgrade"		, name = "keep"				, min = 14 },
			{ type = "upgrade"		, name = "trainingGround" 	, min = 1 },
			{ type = "upgrade"		, name = "dwelling"			, min = 14 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 14 },
			{ type = "upgrade"		, name = "quarrier"			, min = 14 },
			{ type = "upgrade"		, name = "miner"			, min = 14 },
			{ type = "upgrade"		, name = "farmer"			, min = 14 },
			{ type = "upgrade"		, name = "barracks"			, min = 14 },
			{ type = "recruit"		, name = "catapult"	    	, is_record = true },
			{ type = "upgrade"		, name = "wall"				, min = 14 },
			{ type = "upgrade"		, name = "keep"				, min = 15 },
			{ type = "upgrade"		, name = "hunterHall" 		, min = 1 },
			{ type = "upgrade"		, name = "dwelling"			, min = 15 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 15 },
			{ type = "upgrade"		, name = "quarrier"			, min = 15 },
			{ type = "upgrade"		, name = "miner"			, min = 15 },
			{ type = "upgrade"		, name = "farmer"			, min = 15 },
			{ type = "upgrade"		, name = "barracks"			, min = 15 },
			{ type = "explore"		, is_record = true     	   },
			{ type = "upgrade"		, name = "wall"				, min = 15 },
			{ type = "upgrade"		, name = "keep"				, min = 16 },
			{ type = "upgrade"		, name = "stable" 			, min = 1 },
			{ type = "upgrade"		, name = "dwelling"			, min = 16 },
			{ type = "upgrade"		, name = "woodcutter"		, min = 16 },
			{ type = "upgrade"		, name = "quarrier"			, min = 16 },
			{ type = "upgrade"		, name = "miner"			, min = 16 },
			{ type = "upgrade"		, name = "farmer"			, min = 16 },
			{ type = "upgrade"		, name = "barracks"			, min = 16 },
			{ type = "recruit"		, name = "ballista"	    	, is_record = true },
			{ type = "upgrade"		, name = "wall"				, min = 16 },
			{ type = "upgrade"		, name = "keep"				, min = 17 },
			{ type = "upgrade"		, name = "workshop" 		, min = 1  }, }





			